### ISSUE TITLE
JSConsole.com is not working.

### ISSUE THREAD

**Issue by drone540** [remy/jsconsole#101]
This version 2 of JSConsole doesn't seem to work.

GET https://jsconsole.com/remote/test 404 () **internal-commands.js:109** 
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0 **main.00878696.js:6136** 

Where can I access the old version of this site from? or can I download a copy of the old one. This new one doesn't look nearly as good as the old one. It doesn't even have a way to generate the HTML <script> needed for this new version. But apparently it just looks like the file doesn't even exist that it's trying to access.

This is the only easy to use tool for debugging mobile JavaScript errors on iOS and Android devices without requiring to setup random servers running thru node.js just to fix a script error. Should at least have a stable version and a development version running separate for a while. What is version 2 even supposed to do? There isn't any documentation anywhere to find out about the change.

**Comment by remy** [comment]
Remote has been depreciated. It was costing money that no one wanted to pay.

You can access it for the time being at https://1.jsconsole.com - you can donate to the project at https://paypay.me/rem - or with a PR against the new branch.

**Comment by drone540** [comment]
Is Remote a version 1 or 2 thing? And how exactly does it work that increases the cost? Is it just a hosting service you need?

**Comment by remy** [comment]
Hosting service ($25/month), cost of support, development and maintenance. Remote is a v1 thing where I put everything up on my own coin. The cost started at nothing, so the only sensible direction is to either shut the thing down entirely, or get income to support ongoing costs.

**Comment by sradforth** [comment]
Can you just post up a bitcoin address to allow people to donate?  (the paypay.me link doesn't work)

I find your site incredibly helpful for debugging android applications on older devices for instance.  I'm just an indie but happy to pay for the server time I'm using plus a bit to make it worthwhile for you.  You could also show a QR code of bitcoin://{{yourbitcoinaddress}} so people are reminded to contribute each time they use it.  
You can get a simple bitcoin address from something like mycelium, jaxx, electrum apps to copy/paste.  If you want to cash out in your local currency you can either use localbitcoins.com.

**Comment by shoestar** [comment]
It's a typo, the correct link is https://paypal.me/rem

**Comment by crodrigues** [comment]
hi @remy, would you be interested in selling the service incl. domain?

**Comment by remy** [comment]
@crodrigues I'm open to (serious) offers offline at remy@leftlogic.com

**Comment by Borewit** [comment]
@remy, if the service is no longer working, can you please make that clear on [jsconsole.com](https://jsconsole.com/)?

Related #133

**Comment by remy** [comment]
@Borewit I'm confused, why do *I* need to make that change? I mean, the project allows for PRs and I'm not sure it's a problem I've run into (which is why I'm not motivated to change it…)

**Comment by jbis9051** [comment]
@remy  Where is the latest stable version with remote  support? Maybe someone else willing to pay can republish under a different domain. Maybe donateware. I think removing the entire feature was a mistake, especially without any warning on the site.

**Comment by chase-moskal** [comment]
what an interesting tool

i was hoping to use this to do some remote debugging with an ipad from my linux machine.. i'll have to find another solution

@jbis9051, @Borewit 

perhaps the concept of jsconsole could be implemented with webrtc -- such that the connections are peer-to-peer and the infrastructural cost of mediating the webrtc connections would be minimal

i'm assuming jsconsole used to operate with a node server and web sockets?

**Comment by remy** [comment]
No, it used to operate with Ajax and event source so to support the lowest
common denominator.

With webrtc you still need a server for discovery though.

**Comment by Borewit** [comment]
I switched to a tool which did the job locally, forgot which one it was, but it did the job perfect.

Maybe it was [remotedebug-ios-webkit-adapter](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter)

using it with something like:

```batch
npx remotedebug_ios_webkit_adapter --port=9000
```

**Comment by plindelauf** [comment]
I just found out that TrackJS has been so kind to create a similar service for free!

https://remotejs.com/
