### ISSUE TITLE
Is jsconsole.com down?

### ISSUE THREAD

**Issue by vanBersie** [remy/jsconsole#103]
I can't use jsconsole.com as I used it before. Maybe there are just some changes in the new version  but I can't read the documentation: https://jsconsole.com/remote-debugging.html throws a 404.

The `:help` command shows the available commands but now `:listen` seems to require the id. In the past I just typed :listen and got instantly the embed code. That request now throws a 404 as well. 

Will the site be available again soon? Thanks in advance!

**Comment by remy** [comment]
Remote has been depreciated. It was costing money that no one wanted to pay.

You can access it for the time being at https://1.jsconsole.com - you can donate to the project at https://paypay.me/rem - or with a PR against the new branch.

**Comment by shoestar** [comment]
Hey remy, the donation link is https://paypal.me/rem and I just made a small donation. :)

**Comment by remy** [comment]
Thank you! I've got a lot of work coming up until mid nov, but I'll revisit the listen feature to see whether I can port it to V2.
