### ISSUE TITLE
:listen not working ?

### ISSUE THREAD

**Issue by Saturnyn** [remy/jsconsole#105]
Hello,
jsconsole doesn't seem to work at the moment.
If I type ":listen", I get nothing.
In the debugger, I can see a 404 error:

```
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: remote/index.html
RequestId: 34105EB9DD7F2F15
HostId: EzTDAbM84qyLPvpcw3vZUiM2YqPwTMlmOGE0vWFX55h5s9TD1GK9bmlz1FeEMPuwNEVq66dzqBA=
An Error Occurred While Attempting to Retrieve a Custom Error Document

Code: NoSuchKey
Message: The specified key does not exist.
Key: error.html
```

Is it a bug or did I miss something ?
Thanks

**Comment by abadger1406** [comment]
I see same issue:-


![screenshot_2017-10-26_06-30-35](https://user-images.githubusercontent.com/634924/32036365-4aa278da-ba17-11e7-9876-ac8083a2507f.png)

**Comment by remy** [comment]
Listen is deprecated. Sorry. Unless I can get some funds to help Dev
