### ISSUE TITLE
Cannot contain size of console

### ISSUE THREAD

**Issue by JuanPotato** [remy/jsconsole#108]
Referring to the v2 beta, I wanted to confine the height to a certain length. After entering a few commands, the console passes the set height of the div and expands. What can I do to confine it to a certain height? I'm intending to put a script into a bookmarklet so I can have this console injected into sites I want.

**Comment by remy** [comment]
Best to wrap it in a div that you have control of.

**Comment by JuanPotato** [comment]
I should've mentioned that I did do that, and it still passes through. The outer div and div with id root are the correct height. the div inside that is also the correct height. Yet, the divs within _that_ are not the correct height `.react-console-container .Input`
