### ISSUE TITLE
README link to remote debugging info is broken

### ISSUE THREAD

**Issue by aberonni** [remy/jsconsole#110]
When I visit https://jsconsole.com/remote-debugging.html (linked from README) I see:

![image](https://user-images.githubusercontent.com/1260402/33434981-44220670-d5e1-11e7-80fa-12de962c1e6f.png)

**Comment by makc** [comment]
it's not just that link, the whole remote debug is broken.

**Comment by remy** [comment]
Not broken, removed. There's no replacement for the time being. Sorry.
