### ISSUE TITLE
:listen does not work on jsconsole.com

### ISSUE THREAD

**Issue by mathroc** [remy/jsconsole#112]
Hi,

I wanted to try out jsconsole but there’s an issue on jsconsole.com, when typing `:listen`, nothing appears on screen, the network console show a 404 error on "http://jsconsole.com/remote/"

I have not tried this locally yet so I don’t know if it’s an error in this repo or an hosting problem

**Comment by remy** [comment]
Dupe. Please search closed issue. Thanks.
