### ISSUE TITLE
Declaring multiple variables throws TypeError

### ISSUE THREAD

**Issue by Hailiax** [remy/jsconsole#116]
For example, evaluating statement `var x, y;` will throw `TypeError{ e.declarations.peekLast is not a function }`

Tested on jsconsole.com in modern Safari, Chrome, Opera, Firefox.

**Comment by remy** [comment]
Confirmed. (sorry it took a while to reply, I was pretty sure this would be the case, but hadn't had the chance to sit down to try it).

The error is in here somewhere: https://github.com/remy/jsconsole/blob/master/src/node_modules/lib/run.js#L114-L240 I've been getting better at my transforms, so I might be able to find the answer next week.

**Comment by Hailiax** [comment]
Thank you! JSconsole has been really helpful.
