### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by Zibri** [remy/jsconsole#117]
npm install https://github.com/remy/jsconsole -g

npm WARN react-dom@15.6.2 requires a peer of react@^15.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-copy-to-clipboard@5.0.1 requires a peer of react@^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-redux@5.0.6 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none is installed. You must install peer dependencies yourself.

+ @remy/jsconsole@2.1.2

**Comment by remy** [comment]
Just a warning, you can ignore. Or send a PR to upgrade to react@16 :) (which I'll do one day, but it's lopri).
