### ISSUE TITLE
installed but errors out

### ISSUE THREAD

**Issue by Zibri** [remy/jsconsole#118]
I finally managed to install it using yarn instead of npm.
But it errors out.

Steps:
1) install yarn
2) git clone https://github.com/remy/jsconsole
3) yarn install
4) yarn start

it starts correctly and serves on port 3000...

but when I go there with chrome and type: listen I get
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Unhandled Rejection (SyntaxError): Unexpected token < in JSON at position 0
Object._callee5$
src/core/lib/internal-commands.js:111
  108 |   console.clear();
  109 | };
  110 | 
> 111 | const listen = async ({ args: [id], console: internalConsole }) => {
  112 |   // create new eventsocket
  113 |   const res = await fetch(`${API}/remote/${id || ''}`);
  114 |   id = await res.json();

**Comment by remy** [comment]
Listen isn't supported as of V2. (Sorry, yet to document that).

**Comment by Zibri** [comment]
so? how can I use it? at the moment I am using VORLON but I would like to test jsconsole too...

**Comment by remy** [comment]
I think 1.jsconsole.com is still available for the time being.
