### ISSUE TITLE
What happened to the installation instructions?

### ISSUE THREAD

**Issue by r00tk1ll** [remy/jsconsole#121]
I assumed you would just install this using npm install, then run with "node ." as in the previous version but It just gives me an error saying it cant find the jsconsole module even though I'm running this command in the jsconsole root directory.

I also tried changing to the lib folder and running "node app.js" and it starts the server but when I navigate to my localhost:8000 it gives me an error "cant GET /"...

Can you point me in the right direction on the correct procedure to get this running?

Thanks

**Comment by remy** [comment]
git clone. Then npm install, then npm start.
