### ISSUE TITLE
Is jsconsole.com still a things ? 

### ISSUE THREAD

**Issue by yadomi** [remy/jsconsole#123]
Hi, 

As far as I understand with https://github.com/remy/jsconsole/issues/119, https://github.com/remy/jsconsole/issues/115, https://github.com/remy/jsconsole/issues/105, https://github.com/remy/jsconsole/issues/104 and https://github.com/remy/jsconsole/issues/103, jsconsole.com cost you money and you no longer wan't to support it. I understand that. 

However, jsconsole is a great tool, that can help many of people debugging website and more. I don't understand why you would keep the jsconsole.com domain alive, without a clear message telling it just no longer work because of "money". 

There is so many tutorials around the web that tell to use jsconsole but, well when you try it you get a 404 on the `remote.js` script ? If you no longer want to support this project, maybe write in the README it's deprecated or opened for donation, money won't comes by itself.

Also, could you at least add documentation to self-host this project, or alternative to jsconsole ?

Thank you.

**Comment by remy** [comment]
jsconsole.com is a thing. See latest commits for support of maintenance.

Currently hosted at…you guessed it, https://jsconsole.com

Remote is not supported.

**Comment by jonaskohl** [comment]
Or maybe create a small simple solution that users can self host locally?

**Comment by kupietools** [comment]
Having just spent an hour debugging because I didn't know this tool was deprecated, trying to figure out why the remote script call was failing: _Thanks. A lot._

**Comment by youngchief-btw** [comment]
How about hosting this repo with Github Pages? An easy solution to money and servers right? If you don't want to, ill do so myself

**Comment by remy** [comment]
The feature that the OP is referring to (without actually mentioning it)
requires a server backend, it's currently a static site.

**Comment by youngchief-btw** [comment]
Oh, okay
