### ISSUE TITLE
forceUpdate in console.clear() not working under react framework

### ISSUE THREAD

**Issue by bearzx** [remy/jsconsole#130]
I'm borrowing some code from this project to help with building my research prototype. While I was studying the code I noticed that in the components/Console.js there is a `clear()` function that uses `forceUpdate()` after manually set the console state to `{}`. While this works perfectly with preact, it doesn't seem to function in with the actual react. Seems like the `forceUpdate()` function ignores the reset thus the console doesn't clean up itself after calling this function.

I did some tweaks to make it more react-like. Basically I added a lines field to the Console's state so that I could use `this.setState({ lines: {} })` to clean up the lines. That way it will both work with react and preact. I know this doesn't change much but just thought it would be nice to merge it back. Will start a pull request for this.

**Comment by bearzx** [comment]
ah actually just noticed that I'm not authorized to push to this repo. Lol anyway let me know if how I can merge this fix back.

**Comment by remy** [comment]
Merged - thank you 👍
