### ISSUE TITLE
Provide readme 

### ISSUE THREAD

**Issue by Worie** [remy/jsconsole#134]
Readme is empty - I assume that there were some functionalities that are no longer available (remote for example) but it is not clear by simply looking at the repo, you have to dig it up from issues. Even short notes in readme would be helpful

**Comment by ronanharris09** [comment]
Agreed, it'd be more helpful if someone can provide some sort of documentation for this repo.

**Comment by remy** [comment]
@ronanharris09 you're "someone". I agree too.
