### ISSUE TITLE
I'm embedding this to an app

### ISSUE THREAD

**Issue by pvzzombs** [remy/jsconsole#151]
Dear Remy,
   Is it ok for you to allow to use the icon, title, and the main jsconsole for my android app? I'm making an offline android version of this. If you allow, please send me a letter or documentation that you allow me here. Thanks for your good consideration.

**Comment by remy** [comment]
You can, but know that jsconsole is a pwa and already works as an offline
app for Android.

**Comment by pvzzombs** [comment]
@Remy thanks
