### ISSUE TITLE
:listen command gets blocked by CORS (No 'Access-Control-Allow-Origin' header is present on the requested resource)

### ISSUE THREAD

**Issue by thallosaurus** [remy/jsconsole#156]
Everytime I want to use :listen the developer console just throws this error

**Comment by StefanImhoff** [comment]
Same here

**Comment by StefanImhoff** [comment]
`Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://jsconsole.glitch.me/remote/. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).`

**Comment by Cobertos** [comment]
Same, in 2021. Has this not been fixed?

**Comment by quintonn** [comment]
why is this closed?
This is still an issue

**Comment by Giles-W** [comment]
Seeing that people still seem to be able to use this tool and post other issues. What is the work around for this problem?

**Comment by vlad-vovk** [comment]
Same here
