### ISSUE TITLE
Help command not working in Chrome browser

### ISSUE THREAD

**Issue by pacifiquem** [remy/jsconsole#181]
I'm using this jsconsole from chrome web browser and onload it shows that I can use ``help`` command to display helpful command list but it's not working. here is attached image:
![z-error](https://github.com/remy/jsconsole/assets/96472682/3253edb2-a602-4422-b20b-bab4608b91d0)

**Comment by pacifiquem** [comment]
For any misuse or my-side error you can comment @remy.

**Comment by F-loat** [comment]
![image](https://github.com/remy/jsconsole/assets/16759376/ce37394e-6dbd-4674-b709-25deab595856)

**Comment by pacifiquem** [comment]
Thanks @F-loat update docs yet there are some that says that we only have to type `help` not `:help`

**Comment by pacifiquem** [comment]
fixed only issue remaining is to update docs for those typos
