### ISSUE TITLE
:listen doesn't connect

### ISSUE THREAD

**Issue by Askoth** [remy/jsconsole#19]
Hi, sorry to trouble you,

I followed the video on youtube but when I type ":listen" to get the id, it says: "Creating Connection" but that's it. I never get to see the next message with the Id.

I tried firefox 4, safari and chrome. I suppose is some feature in my windows 7 that is wrong? Or does it works only on OSX?

**Comment by olcayertas** [comment]
I am also having same problem. I am trying with `Firefox 49.0.1` on `Mac` and `:listen` doesn't connect.

**Comment by rooseveltdossantos** [comment]
I am also having same problem. I am trying with **Firefox 53.0.2 (64-bit)** on **ArchLinux 1.0**
