### ISSUE TITLE
:listen doesn't connect #2

### ISSUE THREAD

**Issue by Reynicke** [remy/jsconsole#24]
When performing a remote listen I encounter some strange behavior. At first it seemed like it does not connect at all. Then I realized the communication is very, very slow. It takes about 2 minutes until the message "Connected to xxxxxxxxxx" appears. Each log from the remote page again takes minutes to appear in the console in a random order.

This happens in different browsers: Opera, Firefox, Chrome. I don't know how to replicate it. At my workmate's computer it works just fine.

**Comment by stiv-yakovenko** [comment]
":listen" does nothing and usage instruction is missing in the documentation.

**Comment by remy** [comment]
Sorry, shoulda closed this issue. It's unrelated to the current depreciated listen
