### ISSUE TITLE
2 minutes delay...

### ISSUE THREAD

**Issue by JBX028** [remy/jsconsole#36]
Hello,

I have to wait about 2 minutes before to see the console populated ? This is a normal duration ? by looking the video, i can see that the result is almost immediat. However my network connection is fast.... any explanation?

Regards,
Johnny

**Comment by Zibri** [comment]
I can't make it work... I open one chrome tab to jsconsole.com  and enter listen
then I open another tab to an internal host http://10.x.x.x/index.html (which contains the javascript generated from the first tab)
In the second tab I read:
Failed to load resource: the server responded with a status of 404 (Not Found)  remote.js

**Comment by remy** [comment]
Dead issue. Sorry.
