### ISSUE TITLE
quit putting quotes around outputted strings

### ISSUE THREAD

**Issue by Daniel-Hug** [remy/jsconsole#51]
Migrated from: https://github.com/jsbin/jsbin/issues/2086#issuecomment-61684797

IMO the console should quit putting quotes around strings similar to how Firefox's devtools do and follow Chrome's example. Putting quotes around outputted strings is misleading as users could take them to be string literals when they're not.

Here's an example where Chrome's quote free method shines:

```
'as\\"df'  // console input
"as\"df"   // Firefox output | The value changes when evaluated as a string literal: as"df
"as\\"df"  // jsconsole output (evaluated as a string literal this throws a syntax error)
as\"df     // Chrome output
```

**Comment by remy** [comment]
Fixed in latest.
