### ISSUE TITLE
Multiple domain support

### ISSUE THREAD

**Issue by yvg** [remy/jsconsole#52]
@remy was kind enough to share a temporary [URL](https://leftlogic-jsconsole.herokuapp.com/) to support SSL.
jsconsole doesn't seem ready for it as it tries to load content over http once it fires in the running app.
Chrome will output an error like this when it happens:
`
[blocked] The page at 'https://foobar.com' was loaded over HTTPS, but ran insecure content from 'http://remote.html/?BD7C07A2-C379-4D43-B34B-33C9C0825E37': this content should also be loaded over HTTPS.
`

**Comment by remy** [comment]
Closing as fixed in the latest https version :)
