### ISSUE TITLE
Feature Request - "Support Workflow"

### ISSUE THREAD

**Issue by kripper** [remy/jsconsole#57]
In order to use jsconsole for providing support, It would usefull to have this workfow:

1) Client generates a random key
2) Client establishes connection with the server using this key (.../remote.js?$key)
3) Server accepts the connection (server should start listening without executing :listen $key)
4) User provides the $key to the support team
5) Support team accesses the client-device by providing the key (:listen $key or :connect $key if you want to give it other name)

Basically, this is the way how teamviewer and other products work (it's easier to read the key from device and give it to support, than having support giving you the key and having to enter it).

BTW, on the client, you can generate a numeric random key with:

``` javascript
var supportPassword = GenerateRandomString(6, '0123456789');

function GenerateRandomString(length, chars) {
    var result = '';
    for (var i = length; i > 0; --i) result += chars[Math.round(Math.random() * (chars.length - 1))];
    return result;
}
```

and then activate the connection with:

``` javascript
(function(s){s.src='http://imatronix.com:60701/remote.js?' + supportPassword;document.body.appendChild(s)})(document.createElement('script'));
```

The problem is that you need to wait that support executes the :listen command with the key, before activating the connection on the client device.

This could be done with an alert("Please wait...") before trying to activate the connection.

If you could do something to detect a connection failure (because support didn't :listen yet) and retry, it would be usefull to.

**Comment by remy** [comment]
Sorry closing due to part no PRs but also it's probably out of scope.
