### ISSUE TITLE
Enhancement: dynamically generate ID in remote.js and expose to client

### ISSUE THREAD

**Issue by habdelra** [remy/jsconsole#60]
I forked the repo to allow the ID that you can listen on to be dynamically generated in remote.js and then shared with the client as both a string and as a QR code that points to the URL that can be used to launch the console. So tha I don't submit an unsolicited PR, is this something you'd be interested in merging?

Here is a screenshot of how this can be used: 

![image](https://cloud.githubusercontent.com/assets/61075/9154635/a264823e-3e68-11e5-9dbf-401271f36a94.jpg)
![image](https://cloud.githubusercontent.com/assets/61075/9154636/a26eee40-3e68-11e5-8f42-93ca810f29e2.jpg)

**Comment by remy** [comment]
That's cool, but not sure it's totally useful. Since the process is very copy and paste anyway. Maybe ping the project here and I can add it to the readme?
