### ISSUE TITLE
Capture to a log file

### ISSUE THREAD

**Issue by tareco** [remy/jsconsole#61]
Hi,

Can jsconsole log to a file instead of relying on an open browser?

Thanks

**Comment by tareco** [comment]
Ok, I have my own solution:

app.post('/remote/:id/log', function (req, res) {
// (...)
sessions.log[id].write('data: ' + req.body.data + '\neventId:' + (++eventid) + '\n\n');
var fs = require('fs');
fs.writeFile("/tmp/jsconsole.log", 'data: ' + req.body.data + '\neventId:' + (++eventid) + '\n\n', function(err) { if(err) sessions.log[id].write('serverErr: write failed to /tmp/jsconsole.log\n\n); }});
/(...)

Now for the next problem, this only works if I issue the :list command first.. Have to figure out to dinamically create (or get from a hardcoded list) the session ID.

Thanks

**Comment by remy** [comment]
Custom solution looks good 👍
