### ISSUE TITLE
Paths for external library shorcuts are out of date

### ISSUE THREAD

**Issue by pvanb** [remy/jsconsole#62]
<pre>:load underscore</pre> 

results in:

<pre>Failed to load http://documentcloud.github.com/underscore/underscore-min.js</pre>

The following libraries are also out of date:

<pre>
rightjs: Failed to load http://rightjs.org/hotlink/right.js
coffeescript: Failed to load http://jashkenas.github.com/coffee-script/extras/coffee-script.js
</pre>

**Comment by remy** [comment]
Closing as merged (see above).
