### ISSUE TITLE
Google script Only secure origins are allowed

### ISSUE THREAD

**Issue by NeoVance** [remy/jsconsole#66]
When loading over http:
(index):45 Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).(anonymous function) @ (index):45

When loading the page over https, a 404 error when getting sw.js is raised instead.
GET https://jsconsole.com/sw.js net::ERR_FILE_EXISTS

I have not tried the locally hosted version yet, but I have been unable to get remote debugging or injection to work thus far.

**Comment by remy** [comment]
Have you tried switching to https? Do you still have the same issue?

**Comment by difelice** [comment]
**Request URL:** https://jsconsole.com/inject.js
**Request Method:** GET
**Status Code:** 404 
**Remote Address:** 104.18.57.231:443

**Comment by remy** [comment]
Yeah, sorry it should be: https://jsconsole.com/js/inject.js (super old issue too - again, sorry).
