### ISSUE TITLE
It does not work on https (e.g. https://jsconsole.com)

### ISSUE THREAD

**Issue by bdteo** [remy/jsconsole#68]
Because of the following line `origin = document.location.protocol + '//' + lastSrc.substr(7).replace(/\/.*$/, ''),` origin becomes an empty string if lastSrc was  for example =  "https://jsconsole.com/js/remote.js?xxx-xxx-xxx".

**Comment by remy** [comment]
You mean the remote injection or all of jsconsole?

**Comment by bdteo** [comment]
I meant the remote injection. It would really be better to use a regular expression to strip the "http"/"https" instead.

**Comment by remy** [comment]
Remote injection now includes the script as https by default. Thanks.
