### ISSUE TITLE
where is the 'server.js' ?

### ISSUE THREAD

**Issue by Lynn-cc** [remy/jsconsole#73]
I've install the package,and then there's not a file named server.js.How could I run the server locally ?

$ node server.js 8888
module.js:340
    throw err;
    ^

Error: Cannot find module 'D:\cc\jsconsole\jsconsole-master\server.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by Lynn-cc** [comment]
I've install the package,and then there's not a file named server.js.How could I run the server locally ?

**Comment by armivit** [comment]
There are no server.js file. You can start the server by

`$ node lib/app.js`

(port 8000 by default) or with custom port

`$ PORT=8888 node lib/app/js`
