### ISSUE TITLE
html on harddisk does not connect correctly

### ISSUE THREAD

**Issue by digi604** [remy/jsconsole#74]
[Error] Failed to load resource: The requested URL was not found on this server. (remote.html, line 0):

file:///remote.html?e6916321-8659-4720-a028-1114d9eb2bce

There should probably be a check if the file is on file://

**Comment by digi604** [comment]
This issue is bothersome if you try to debug mobile web views that are hosted in the application

**Comment by remy** [comment]
No, pretty sure assets severed over file protocol won't work (i.e. not supported).
