### ISSUE TITLE
Injection broken due to inject.js going missing

### ISSUE THREAD

**Issue by stuartpb** [remy/jsconsole#75]
As alluded to in https://github.com/remy/jsconsole/issues/66#issuecomment-219896798, requesting http://jsconsole.com/inject.js or https://jsconsole.com/inject.js yields a 404 response, with the body:

```
{"code":"ResourceNotFound","message":"/inject.js"}
```

This makes it so [the bookmarklet](https://jsconsole.com/inject.html) is no longer functional.

**Comment by cdes** [comment]
inject.js went away again 😢 

![image](https://user-images.githubusercontent.com/1207863/70854848-62eebd00-1ed2-11ea-9681-02c5e864b5c0.png)
