### ISSUE TITLE
add server.js

### ISSUE THREAD

**Issue by lovetingyuan** [remy/jsconsole#80]
```javascript
'use strict';
const fs = require('fs');
process.env.PORT = process.argv[2] || 8000;
fs.readFile('lib/app.js', (err, data) => {
    if (err) throw err;
    if (data.indexOf('"use strict"') !== 0) {
        fs.writeFileSync('lib/app.js', '"use strict";\n' + data);
    }
    require('./lib/app');
    setTimeout(function() {
    	let address = 'http://127.0.0.1:' + process.env.PORT;
    	require('child_process').exec('start ' + address);
    	console.log('start browser at ' + address);
    });
});
```

**Comment by lovetingyuan** [comment]
1. save the code above as server.js 
2. use `node server ${port}` to start jsconsole server

**Comment by remy** [comment]
There's no need for this code. PORT can be set on the CLI via `PORT=8001 node .` but thanks none the less.

**Comment by lovetingyuan** [comment]
ok, I agree with you, but could you add 'use strict' in the app.js ? or nodejs will throw error 'SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode', thank you!

**Comment by remy** [comment]
Oh, the package dictates that the engine should be node@6 which doesn't require the `use strict` statement.
