### ISSUE TITLE
https://jsconsole.com get a net::ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by PaykomanVll** [remy/jsconsole#83]
Hello,

as first i must say is a very nice tool, i have test it for few weeks.
But now i will debug again and it work not more :(

i get this errors on my browser:
````
GET https://jsconsole.com/remote/5d3bcc15-a686-4250-bd87-cc1d8e09777f/run net::ERR_CONNECTION_CLOSED
https://jsconsole.com/remote/5d3bcc15-a686-4250-bd87-cc1d8e09777f/log Failed to load resource: net::ERR_CONNECTION_CLOSED
````

i hope you can fix or help.

Best regards,
Stefan

**Comment by remy** [comment]
Something causes jsconsole to break, but I'm not sure what it is. If you can replicate consistently, please let me know.

**Comment by andertun** [comment]
@remy It happens for me at the moment. 

I just used `:listen` and pasted the script tag into my page. It worked well yesterday.

![screenshot 2017-03-30 12 11 19](https://cloud.githubusercontent.com/assets/1045799/24499445/0a3f1dae-1542-11e7-8ce0-1cb475c55c70.png)

**Comment by epzilla** [comment]
@andertun I'm seeing this as well.

**Comment by remy** [comment]
This is back online for the time being.
