### ISSUE TITLE
remote sessions

### ISSUE THREAD

**Issue by basvanmeurs** [remy/jsconsole#84]
Tried to install it by cloning this repository, running npm install and then the node server.js.

The page loads up, and I can get a key but when including the script in a remote page it never seems to connect to the server. I can see in the network tabs that both the dashboard and the remote page are connected to port 8000. When I debug it seems that both pages get a 'session' with the same id and they overwrite each other.

I am using chrome though I doubt it will matter.

**Comment by remy** [comment]
I've updated your issue title, since "it" wasn't particularly clear.

I can't really help you other than suggest you take a look at the code (it's relatively small) or just use the online version. Thanks.

**Comment by basvanmeurs** [comment]
It was not the best description indeed.

I actually did take a look at the source code but I noticed that both the host and the client seem to overwrite each other's 'session'. I am confused by that bit because it seems as such a fundamental thing going wrong. Does it run ok on your local machine?

**Comment by remy** [comment]
Yes, IIRC. Though I tend to rely on the live version since it means I don't
have to spin it up locally.

Just out of interest, why are you trying to run locally (entirely for my
own interest).

**Comment by basvanmeurs** [comment]
Because the online version does also not work I wanted to try it out locally.

**Comment by basvanmeurs** [comment]
If it does work for you, please let me know and I will create a screen recording to show the issue.

**Comment by remy** [comment]
Just asking why you're trying to run locally.

My primary concern is live.

**Comment by basvanmeurs** [comment]
I mean: if production works for you I can create a screen recording of **production**. If I can use production, that would be fine.

**Comment by remy** [comment]
Got it. I'll take a look at production to be sure again later this morning
(I'm replying from the gym atm!)

**Comment by remy** [comment]
Okay, there's something definitely up. I can't complete a session loop in production, so I'm debugging now.

**Comment by remy** [comment]
Should be fixed. Note that I'm _thinking_ about charging (possibly as a one off) for the remote service (to help with server bills), so make use of it whilst it's still free!! :)

It broke when I moved to a new system recently, but I had to do a bunch of fixes to get it back again.
