### ISSUE TITLE
Can't open https://jsconsole.com on iOS

### ISSUE THREAD

**Issue by awerlang** [remy/jsconsole#85]
Hey, I use this magnificent tool whenever I need to track down an issue on iOS mobile. But it isn't working today.

I open http://jsconsole.com on Safari, it redirects to https, but then it doesn't connect. Chrome on safari returns ERR_SSL_PROTOCOL_ERROR. With IP it's the same thing.

Also, it fails SSL validation: https://www.ssllabs.com/ssltest/analyze.html?d=jsconsole.com

**Comment by remy** [comment]
Try again now. I was just porting to a new server. I'm confident it's okay now.

**Comment by awerlang** [comment]
Yep, thanks a lot!
