### ISSUE TITLE
jsconsole.com completly broken (deleted files?)

### ISSUE THREAD

**Issue by Aquazus** [remy/jsconsole#93]
Okay, it seems like some files on jsconsole.com got deleted and the whole thing is broken.
If anyone want to use JSConsole while remy fix it, I've hosted a mirror:
https://jsconsole.aquazus.fr/

**Comment by remy** [comment]
Which files? I use jsconsole a lot and haven't had any issues, but then, you've not really specified what it is that was broken.

**Comment by MKindy** [comment]
I don't know about files, but I am only getting "502: An error occurred with your deployment" on jsconsole.com.

**Comment by remy** [comment]
Hmm. Okay. Can you send me a screenshot (including URL). I get the whole
thing loading, but its entirely possible that the service worker is hiding
this problem for me (though i tend to clear out regularly to retest).

**Comment by MKindy** [comment]
Did my screenshot in the previous post not come out?  Try this:  http://imgur.com/a/8fFDm

**Comment by remy** [comment]
Fixed.

**Comment by Aquazus** [comment]
Still not working
http://i.imgur.com/XP8jwYY.png

**Comment by punkoffice** [comment]
I have the same problem as @Aquazus with the same errors.  jsconsole is no longer working for me in Chrome

**Comment by remy** [comment]
By doesn't work, specifically you mean the remote injection, rather than
jsconsole itself.

No one try to look at the code yet? I mean, i would, but I'm busy with paid
client work (and don't need to use the remote injection feature of
jsconsole right now).

**Comment by fierysolid** [comment]
This is still broken FYI. Getting the 502 bad gateway

**Comment by shoestar** [comment]
I also get 502 for https://jsconsole.com/ on Chrome and Edge but not on Firefox or Opera.

And I get 404 for https://jsconsole.com/inject.html, https://jsconsole.com/remote-debugging.html and most important https://jsconsole.com/js/remote.js?some-random-id on all browsers.

**Comment by remy** [comment]
Yeah, server keeps borking. It'll 404 on any URL except root whilst it's 50x'ing.

**Comment by remy** [comment]
Back online for the time being.

**Comment by bogomips** [comment]
still same error

**Comment by Enalmada** [comment]
same error

**Comment by nielsenvancura** [comment]
I was fine yesterday, today I am getting this too. Tested various sessions

**Comment by remy** [comment]
Server has blown. Will need to look into why. Hold your horse (maybe get
them a cake or something, it'll be a few hours).

**Comment by oleole90** [comment]
Ahem, [jsconsole.com/remote-debugging.html](https://jsconsole.com/remote-debugging.html) [404]

**Comment by remy** [comment]
Yep. Known. Cheers.

**Comment by Aquazus** [comment]
Still broken, :listen doesn't answer anything

**Comment by remy** [comment]
@aquazus - no, it's depreciated. Use 1.jsconsole.com but know that that service will be retired eventually
