### ISSUE TITLE
Feature Request - "Support coloring"

### ISSUE THREAD

**Issue by balexandre** [remy/jsconsole#95]
`console.log()` provides the ability to **color messages**, it would be lovely if that would translate in the jsconsole window

as today, the output is:

![](http://s6.postimg.org/wd3f8jjfl/screenshot_65.png)

in contrast to a **more readable** version in Desktop Chrome:

![](http://s6.postimg.org/y66bwv4m9/screenshot_66.png)

**Comment by remy** [comment]
I'm working on a new version, and was able to get styled logging in here:
<img width="632" alt="screen shot 2017-05-31 at 08 48 32" src="https://cloud.githubusercontent.com/assets/13700/26621248/0a527558-45de-11e7-87e1-99b292fc40f9.png">

It's a little while out before releasing, but it was straight forward to support.
