### ISSUE TITLE
JSConsole.com is down : "502  An error occured with your deployment."

### ISSUE THREAD

**Issue by amangeot** [remy/jsconsole#97]
Hello,
first of all, thanks for the great tool you provide.

Just to let you know, today I was trying to access jsconsole.com and got the following error message : 
> 502 An error occured with your deployment.

**Comment by remy** [comment]
Can you try 2.jsconsole.com in the mean time? (Am on holiday and can't
redeploy)

**Comment by amangeot** [comment]
Awesome, thank you for replying that fast !

No issues loading https://2.jsconsole.com, though when I enter the command `:listen`, it doesn't validate the command, and the debugger shows : 
> GET https://2.jsconsole.com/remote/ 404 ()
and next to it : 
> Uncaught (in promise) SyntaxError: Unexpected end of JSON input | Promise rejected (async)

Sorry for bringing up troubles during your holidays,

**Comment by hassanbsc** [comment]
What I did is to install it on my local machine using npm.

**Comment by cocowalla** [comment]
@amangeot were you able to get it working yet?

**Comment by amangeot** [comment]
Not yet, but I will definitely try to run it on my local machine, when I get back to it, as @hassanbsc did.

**Comment by cocowalla** [comment]
Unfortunately not an option for me, my machine is totally locked down :(

**Comment by amangeot** [comment]
Oh :/ 
Maybe have it run on a host like http://modulus.io/ ?

Well for others coming here, if you can, it works like a charm on localhost.

Though I'm trying to debug an iPhone 4 Safari, but I can't get the logs from Safari iPhone 4. 
I'm not sure if it comes from my setup or from the browser.

**Comment by remy** [comment]
up.
