### ISSUE TITLE
YQL is broken

### ISSUE THREAD

**Issue by pkit** [remy/jsconsole#98]
/**/loadDOM1504532716939({"query":{"count":"0","created":"2017-09-04T13:45:17Z","lang":"en-US","meta":{"message":"html table is no longer supported. See https://policies.yahoo.com/us/en/yahoo/terms/product-atos/yql/index.htm for YQL Terms of Use"}},"results":[]});

**Comment by remy** [comment]
Pretty sure yql got killed off a good few years ago. Will close, and look at alternatives, though I'm not sure there's any.
